### ISSUE TITLE
backup rsync parameter H und E?!

### ISSUE THREAD

**Issue by technikamateur** [technikamateur/FreeMind#21]

**Comment by vale981** [comment]
H ist generell gefaerlich und sollte nicht noetig sein, da du warscheinlich keine hard-links verwendest.
E kannst du reinhauen, wenn du UNIX programme in der share speicherst/installierst, ansonsten nonsens und attac vector.

Verdict: Ohne H und E...

**Comment by vale981** [comment]
-l koennte gut sein
