### ISSUE TITLE
recycleready und backupready dynamisieren

### ISSUE THREAD

**Issue by technikamateur** [technikamateur/FreeMind#34]
- Detektieren, wenn HDD nicht online
- per anacron o.Ä. Diese Informationen dann verarbeiten und die beiden Infos einfach mal anpassen

**Comment by vale981** [comment]
Ist implementiert. Ohne Anacron und in RealTime.

Wenn der Raspi nachfragt, werden die caches automatisch geloescht und der Status wird brandaktuell abgefragt.

**Comment by technikamateur** [comment]
und was ist mit recyleready?

**Comment by vale981** [comment]
erleuchte mich bitte und zeige mir, wie das recycleready functionieren soll...

**Comment by technikamateur** [comment]
Wir telefonieren mal.
