### ISSUE TITLE
Implement a onSuccess log, espacially if an error hasn't occurred again...

### ISSUE THREAD

**Issue by vale981** [technikamateur/FreeMind#40]

**Comment by technikamateur** [comment]
Was ist denn damit? Hast dur dir in eine TODO geschrieben:

Check todos in the project with grep -R todo...
Some modularizing around the actions has to be done...

**Comment by vale981** [comment]
Done

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vale981** [comment]
Done

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vale981** [comment]
Done

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vale981** [comment]
Done

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vale981** [comment]
Done

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vale981** [comment]
Das gehört hier nicht hin

_Sent from my Sony D6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
